project:
  type: website

website:
  title: "StepuP Newsletter"
  # cookie-consent: true
  navbar:
    background: primary
    pinned: true
    left:
      - text: Aktueller Newsletter
        href: v4.qmd
      - text: Ãœber StepuP
        href: about.qmd
  
  sidebar: 
    sytle: docked
    contents:
      - text: Newsletter 4
        href: v4.qmd
      - text: Newsletter 3
        href: v3.qmd
      - text: Newsletter 2
        href: v2.qmd
      - text: Newsletter 1 
        href: v1.qmd

    right:
    - icon: envelope
      aria-label: email
      href: "mailto:j.welzel@neurologie.uni-kiel.de?subject=StepuP%20Newsletter"

  page-footer: 
    left: "Copyright 2023, Julius Welzel" 


format:
  html:
    theme: [lux, rwds.scss]
    css: rwds.css
    fontsize: 1.2em